# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.9"

env: {% if '2.1' in cookiecutter.django_versions %}
  - TOX_ENV=py37-django-21
  - TOX_ENV=py36-django-21
  - TOX_ENV=py35-django-21{% endif %}{% if '3.1' in cookiecutter.django_versions %}
  - TOX_ENV=py39-django-31
  - TOX_ENV=py38-django-31
  - TOX_ENV=py37-django-31{% endif %}{% if '3.2' in cookiecutter.django_versions %}
  - TOX_ENV=py39-django-32
  - TOX_ENV=py38-django-32
  - TOX_ENV=py37-django-32{% endif %}{% if 'master' in cookiecutter.django_versions %}
  - TOX_ENV=py35-django-master
  - TOX_ENV=py36-django-master{% endif %}

matrix:
  fast_finish: true{% if 'master' in cookiecutter.django_versions %}
  allow_failures:
    - env: TOX_ENV=py35-django-master
    - env: TOX_ENV=py36-django-master{% endif %}

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
